# https://github.com/P3TERX/ActionsVM

name: Ubuntu (tmate)

on:
  repository_dispatch:
    types: [ubuntu]
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Start SSH via tmate
      uses: P3TERX/ssh2actions@main
